// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Storyly.Maui.Demo
{
    static class Constants
    {
        public const string StorylyToken = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NfaWQiOjc2MCwiYXBwX2lkIjo0MDUsImluc19pZCI6NDA0fQ.1AkqOy_lsiownTBNhVOUKc91uc9fDcAxfQZtpm3nj40";
        public const string VerticalFeedToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NfaWQiOjIzODAsImFwcF9pZCI6MjA1MTEsImluc19pZCI6MjI5NDJ9.TXCs-M6guskLJA1JXmu7PlmPxUKfyw88lBpOdxmgpDI";
    }

    public partial class ViewController : UIViewController
    {
        public ViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            // Perform any additional setup after loading the view, typically from a nib.

            var storylyView = new StorylyView(new CGRect(0, 90, 414, 50))
            {
                StorylyInit = new StorylyInit(
                    Constants.StorylyToken,
                    new StorylyBuilder().Build()),
                RootViewController = this,
                Delegate = new StorylyDelegateImpl()
            };
            View.AddSubview(storylyView);

            var storylyViewCustomization = new StorylyView(new CGRect(0, 210, 414, 80))
            {
                StorylyInit = new StorylyInit(
                    Constants.StorylyToken,
                    new StorylyBuilder()
                        .SetStoryGroupStyling(new StorylyStoryGroupStylingBuilder().SetSize(StoryGroupSize.Small)
                        .SetCustomGroupViewFactory(new CustomStoryGroupViewFactory())
                            .Build())
                    .Build()),
                RootViewController = this,
                Delegate = new StorylyDelegateImpl()
            };
            View.AddSubview(storylyViewCustomization);

            var verticalFeedBarView = new StorylyVerticalFeedBarView(new CGRect(0, 300, 414, 150))
            {
                StorylyVerticalFeedInit = new StorylyVerticalFeedInit(
                   Constants.VerticalFeedToken,
                   new StorylyVerticalFeedConfigBuilder()
                   .SetVerticalFeedGroupStyling(new StorylyVerticalFeedGroupStylingBuilder()
                   .SetIconHeight(150)
                   .Build())
                   .Build()),
                RootViewController = this,
                StorylyVerticalFeedDelegate = new VerticalFeedDelegateImpl()
            };
            View.AddSubview(verticalFeedBarView);

            var verticalFeedView = new StorylyVerticalFeedView(new CGRect(0, 500, View.Frame.Width, View.Frame.Height - 450))
            {
                StorylyVerticalFeedInit = new StorylyVerticalFeedInit(
                   Constants.VerticalFeedToken,
                   new StorylyVerticalFeedConfigBuilder()
                   .SetVerticalFeedBarStyling(new StorylyVerticalFeedBarStylingBuilder()
                   .SetSection(3)
                   .Build())
                   .Build()),
                RootViewController = this,
                StorylyVerticalFeedDelegate = new VerticalFeedDelegateImpl()
            };
            View.AddSubview(verticalFeedView);

            var presenterView = new StorylyVerticalFeedPresenterView(new CGRect(0, 0, View.Frame.Size.Width, View.Frame.Size.Height))
            {
                StorylyVerticalFeedInit = new StorylyVerticalFeedInit(
                   Constants.StorylyToken,
                   new StorylyVerticalFeedConfigBuilder().Build()),
                RootViewController = this,
            };

            UIButton button = new UIButton(UIButtonType.System);
            button.Frame = new CGRect(View.Frame.Width - 200, 50, 200, 50);
            button.SetTitle("Toogle Presenter", UIControlState.Normal);

            button.TouchUpInside += (sender, e) =>
            {
                if ( presenterView.Superview != null ) {
                    presenterView.RemoveFromSuperview();
                }
                else
                {
                    View.AddSubview(presenterView);
                    View.BringSubviewToFront(button);
                }
            };

            View.AddSubview(button);
        }
    }

    public partial class StorylyDelegateImpl : StorylyDelegate
    {
        public override void StorylyLoaded(StorylyView storylyView, StoryGroup[] storyGroupList, StorylyDataSource dataSource)
        {
            Console.WriteLine($"StorylyLoaded:SGSize:{storyGroupList.Length}");
        }

        public override void StorylyActionClicked(StorylyView storylyView, UIViewController rootViewController, Story story)
        {
            Console.WriteLine($"StorylyActionClicked:ActionUrl:{story.ActionUrl}");
        }

        public override void StorylyEvent(StorylyView storylyView, Storyly.StorylyEvent @event, StoryGroup storyGroup, Story story, StoryComponent storyComponent)
        {
            Console.WriteLine($"StorylyEvent:StorylyEvent:");
            if (storyComponent != null)
            {
                if (storyComponent.Type == StoryComponentType.Emoji)
                {
                    StoryEmojiComponent emojiComponent = (StoryEmojiComponent)storyComponent;
                    if (emojiComponent != null)
                    {
                        Console.WriteLine($"StorylyEvent:StoryEmojiComponent:{emojiComponent.CustomPayload}");
                    }
                }
            }
        }
    }

    public partial class VerticalFeedDelegateImpl : StorylyVerticalFeedDelegate
    {
        public override void VerticalFeedLoaded(STRVerticalFeedView view, VerticalFeedGroup[] feedGroupList, StorylyDataSource dataSource)
        {
            Console.WriteLine($"StorylyLoaded:SGSize:{feedGroupList.Length}");
        }

        public override void VerticalFeedActionClicked(STRVerticalFeedView view, UIViewController rootViewController, VerticalFeedItem feedItem)
        {
            Console.WriteLine($"StorylyActionClicked:ActionUrl:{feedItem.ActionUrl}");
        }

        public override void VerticalFeedEvent(STRVerticalFeedView view, Storyly.VerticalFeedEvent @event, VerticalFeedGroup feedGroup, VerticalFeedItem feedItem, VerticalFeedItemComponent feedItemComponent)
        {
            Console.WriteLine($"StorylyEvent:StorylyEvent: {@event}");
            if (feedItemComponent != null)
            {
                if (feedItemComponent.Type == VerticalFeedItemComponentType.Emoji)
                {
                    VerticalFeedEmojiComponent emojiComponent = (VerticalFeedEmojiComponent)feedItemComponent;
                    if (emojiComponent != null)
                    {
                        Console.WriteLine($"StorylyEvent:StoryEmojiComponent:{emojiComponent.CustomPayload}");
                    }
                }
            }
        }
    }

    public class CustomStoryGroupViewFactory : StoryGroupViewFactory
    {
        public override StoryGroupView CreateView
        {
            get
            {
                return new XamarinStoryGroupView(new CustomerStoryGroup());
            }
        }
        public override CGSize GetSize
        {
            get
            {
                return new CGSize(200, 50); // Replace with your actual view size
            }
        }
    }
    public class CustomerStoryGroup : XamarinStoryGroup
    {
        private UILabel titleLabel = new UILabel()
        {
            TranslatesAutoresizingMaskIntoConstraints = false,
            TextAlignment = UITextAlignment.Center
        };

        private UIView container = new UIView()
        {
            TranslatesAutoresizingMaskIntoConstraints = false,
        };

        public override UIView CreateView
        {
            get
            {
                container.Layer.CornerRadius = 16;
                container.AddSubview(titleLabel);

                titleLabel.TopAnchor.ConstraintEqualTo(titleLabel.Superview.TopAnchor).Active = true;
                titleLabel.BottomAnchor.ConstraintEqualTo(titleLabel.Superview.BottomAnchor).Active = true;
                titleLabel.LeadingAnchor.ConstraintEqualTo(titleLabel.Superview.LeadingAnchor).Active = true;

                return container;
            }
        }
        public override void PopulateView(StoryGroup? storyGroup)
        {
            titleLabel.Text = storyGroup?.Title;
            if (storyGroup?.Seen == true)
            {
                container.BackgroundColor = UIColor.Red.ColorWithAlpha(0.5f);
            }
            else
            {
                container.BackgroundColor = UIColor.Red.ColorWithAlpha(1f);
            }
        }
    }
}
