require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'StorylyDemo' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'storyly-react-native', :path => '../node_modules/storyly-react-native'

  target 'StorylyDemoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end

target 'StorylyDemo-tvOS' do
  # Pods for StorylyDemo-tvOS

  target 'StorylyDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

dynamic_frameworks = ['Storyly', 'SDWebImage']
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if dynamic_frameworks.include?(pod.name)
      def pod.dynamic_framework?;
        true
      end
      def pod.build_type;
        Pod::BuildType.dynamic_framework
      end
    end
  end
end