source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target 'StorylyDemo' do
  pod 'SDWebImage'
  pod 'Storyly', '~> 1.22.0'
  pod 'StorylyMonetization', '~> 1.1.0'
end
